// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0FIWi9eJ_f1ebCUDI8zC-xt2nCRJvetk',
    appId: '1:543139785376:web:d3e912d4896bf0ebd9f7c5',
    messagingSenderId: '543139785376',
    projectId: 'anapay-task',
    authDomain: 'anapay-task.firebaseapp.com',
    storageBucket: 'anapay-task.firebasestorage.app',
    measurementId: 'G-HXKBNY2K0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_mvW2ixlPJMaMpzfAonjT1QFulNQShvk',
    appId: '1:543139785376:android:8a931b9b5c5580b9d9f7c5',
    messagingSenderId: '543139785376',
    projectId: 'anapay-task',
    storageBucket: 'anapay-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhyOe4JTbeJ7CjcJQAlrwiI8YFc42RWo',
    appId: '1:543139785376:ios:057221d256272138d9f7c5',
    messagingSenderId: '543139785376',
    projectId: 'anapay-task',
    storageBucket: 'anapay-task.firebasestorage.app',
    iosClientId:
        '543139785376-9gj1nnrahi6994khtguk7crbp46k1gfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.anapayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0FIWi9eJ_f1ebCUDI8zC-xt2nCRJvetk',
    appId: '1:543139785376:web:35f16f554eb566e2d9f7c5',
    messagingSenderId: '543139785376',
    projectId: 'anapay-task',
    authDomain: 'anapay-task.firebaseapp.com',
    storageBucket: 'anapay-task.firebasestorage.app',
    measurementId: 'G-C9FDYVXV16',
  );
}
